### PR TITLE
fix ruby deprecation warning

### PR DESCRIPTION
**Pull request by cody-elhard**

### CODE REVIEW

**Comment by mikz** [comment]
It is possible this can crash in some cases. See 

```
irb(main):001:0> /foo/.match(Object.new)
Traceback (most recent call last):
        5: from /Users/mikz/.rubies/ruby-2.7.1/bin/irb:23:in `<main>'
        4: from /Users/mikz/.rubies/ruby-2.7.1/bin/irb:23:in `load'
        3: from /Users/mikz/.rubies/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/irb-1.2.3/exe/irb:11:in `<top (required)>'
        2: from (irb):1
        1: from (irb):1:in `match'
TypeError (no implicit conversion of Object into String)
```

Would be good to know if those cases that trigger the warning are covered in the test suite.
I don't see it triggered in the build https://travis-ci.org/github/formtastic/formtastic/jobs/720662700

**Review by mirelon — APPROVED** [review]

**Comment by deivid-rodriguez** [comment]
Hi! Can you try 4.0.0.rc1 and see if this issue is fixed there?

**Comment by tute** [comment]
No warnings! See https://github.com/formtastic/formtastic/pull/1315#issuecomment-736542793. Thanks!

**Comment by mikz** [comment]
Fixed by https://github.com/formtastic/formtastic/pull/1315

**Pull request closed without merging**
