### PR TITLE
Fix i18n for enums inside nested forms

### LINKED ISSUE #1151: collection_from_enum I18n unusable with has_many nested forms
the `collection_from_enum` method try to fetch translation with the following key: 

``` ruby
key = "activerecord.attributes.#{object_name}.#{method_name.pluralize}.#{name}"
```

In case where the field is in a has_many nested (eg: with cocoon) form, object_name can be like this : 

``` ruby
car[wheels_attributes][0]
```

So it is impossible to use the translation.
I suggest to change object_name by `model_name.underscore` or something like this to obtain just the model name as expected to use in the translation yml file.

### PR DESCRIPTION
**Pull request by arokettu**
This fixes #1151

### CODE REVIEW

**Comment by sandfoxme** [comment]
The idea is that `key = "activerecord.attributes.#{object_name}.#{method_name}"` is not really a correct way to get activerecord i18n data, there is a discovery algorithm that also looks for object ancestors

The algorithm is a part of ActiveModel

here is the method itself taken from 

```
    def human_attribute_name(attribute, options = {})
      options   = { count: 1 }.merge!(options)
      parts     = attribute.to_s.split(".")
      attribute = parts.pop
      namespace = parts.join("/") unless parts.empty?
      attributes_scope = "#{self.i18n_scope}.attributes"

      if namespace
        defaults = lookup_ancestors.map do |klass|
          :"#{attributes_scope}.#{klass.model_name.i18n_key}/#{namespace}.#{attribute}"
        end
        defaults << :"#{attributes_scope}.#{namespace}.#{attribute}"
      else
        defaults = lookup_ancestors.map do |klass|
          :"#{attributes_scope}.#{klass.model_name.i18n_key}.#{attribute}"
        end
      end

      defaults << :"attributes.#{attribute}"
      defaults << options.delete(:default) if options[:default]
      defaults << attribute.humanize

      options[:default] = defaults
      I18n.translate(defaults.shift, options)
    end
```

**Comment by sandfoxme** [comment]
The fix is not final, it fails some tests. But I hope it is the direction in which we should look

**Comment by sandfoxme** [comment]
* fixed one bug with i18n fallbacks
* classes in tests now also mock ActiveModel::Name and lookup_ancestors
* added a test for ancestor translation lookup

tests are passing now. seems final enough

**Comment by sandfoxme** [comment]
Reverted some changes in tests: Post already uses ActiveModel::Naming and MongoPost has nothing to do with the task

**Comment by avaz** [comment]
Hey guys,

Any idea when this will be available?

Thanks!

**Comment by Nghi93** [comment]
any updates on this?

**Comment by mikz** [comment]
We could aim to have this in 4.0. Would it help the situation to support only Rails 5+?
I don't really like the fact that we would copy a rails method inside formtastic, so it would be better to just reuse what is there in Rails.

Also, I'd like to have a clean git history, so the whitespace changes should be applied in different PR for easier review.

**Comment by sandfoxme** [comment]
Could anyone take it from me? I don't even work with ruby currently

**Comment by Fs00** [comment]
Hello everyone. If the maintainers (@justinfrench @deivid-rodriguez) are still interested in merging a fix, I would like to propose a simpler solution to this issue in another PR.
I've stumbled upon it earlier today and has been pretty annoying.

**Comment by mikz** [comment]
@Fs00 I think that would be awesome! Would be awesome if it could use Rails API as much as possible, so we don't have copy a method implementation. And I guess and explanation what the problem is with some examples would be awesome :) Thank you for doing this!

**Comment by Fs00** [comment]
@mikz This can now be closed since #1342 has been merged :)

**Comment by mikz** [comment]
Fixed by #1342

**Pull request closed without merging**
