### PR TITLE
 hotfix: Fix deprecated method warning.

### PR DESCRIPTION
**Pull request by lanzhiheng**
fixes: #1314

### CODE REVIEW

**Comment by mauro-oto** [comment]
@justinfrench any chance you could review this PR? Thank you!

**Comment by mauro-oto** [comment]
Ping @mikz, would you have some time to review this fix? Thank you! 🙏

**Comment by tute** [comment]
There's a new duplicate here: https://github.com/formtastic/formtastic/pull/1317

**Comment by mikz** [comment]
Hey. I prefer https://github.com/formtastic/formtastic/pull/1317 as it is in the spirit of the original code.
But as mentioned there, I believe this code path is not triggered in the test suite as I can't see the deprecation warning in the test log.
I think it needs a test case to trigger the behaviour and then fix it to make sure we are not breaking anything.

**Comment by deivid-rodriguez** [comment]
Hi! Can you try 4.0.0.rc1 and see if this issue is fixed there?

**Comment by tute** [comment]
I can confirm there are warnings with 3.1.5 but not with 4.0.0.rc1. I also have tests failing but I'm not sure whether they are directly related with the upgrade, and I believe that's independent. Thanks!

**Comment by deivid-rodriguez** [comment]
Thanks for confirming @tute, I'll close this, then.

**Comment by deivid-rodriguez** [comment]
Actually I don't have permissions. @mikz can you close this and the other PR?

**Comment by mikz** [comment]
Does someone have the commit/PR that fixed it?

Closing. Fixed in https://github.com/formtastic/formtastic/releases/tag/4.0.0.rc1

**Comment by deivid-rodriguez** [comment]
I don't... It'd be a matter of running a `git bisect`, I guess.

**Comment by justinfrench** [comment]
@mikz @deivid-rodriguez I think I've fixed your permissions dos that you can close issues (among many other things) ;)

**Comment by deivid-rodriguez** [comment]
Thanks so much @justinfrench! Closing this then :)

**Pull request closed without merging**
